version: "3"

services:
  django:
    build:
      context: .
    container_name: django
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=todo123
      - DEBUG=True
      - SECRET_KEY=<create your own secret key and put here>
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=todo123
      - POSTGRES_DB=app
  celery:
          build: .
          environment:
                - DB_HOST=db
                - DB_NAME=app
                - DB_USER=postgres
                - DB_PASSWORD=todo123
                - DEBUG=True
                - SECRET_KEY=<create your own secret key and put here>
                - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
                - CELERY_BROKER=redis://redis:6379/0
                - CELERY_BACKEND=redis://redis:6379/0
          command: celery -A todo worker -l INFO
          volumes:
              - .:/app
          depends_on:
              - django
              - redis
  redis:
    image: "redis:alpine"
