version: "3"

services:
  django:
    build:
      context: .
    container_name: django
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - /.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    env_file:
      - /.env
  celery:
    build: .
    env_file:
      - /.env
    command: celery -A todo worker -l INFO
    volumes:
        - .:/app
    depends_on:
        - django
        - redis
  redis:
    image: "redis:alpine"
